### ISSUE TITLE
3D GPS/IMU data

### ISSUE THREAD

**Issue by hqtang-git** [dohyeoklee/EKF-kitti-GPS-IMU#1]
Hi @dohyeoklee 
Do you have the total 3D GPS/IMU data of KITTI? Can you share with me?
I want to download the  3D GPS/IMU data (location, speed, acceleration, meta information, stored as text file), but I don't know where to go.

**Comment by dohyeoklee** [comment]
Dear @hqtang-git 

please go to http://www.cvlibs.net/datasets/kitti/raw_data.php
and you can see this page.

![fig1](https://user-images.githubusercontent.com/72516929/125099920-84964180-e113-11eb-87af-c8c0e25c6023.png)

and there is two download link for data like above figure. 'unsynced' means literally unsynced(for time) with multiple sensors(GPS, IMU, etc). 'synced' means they are filtered with each other. For this repository, I use synced data for ground truth.
If you download one of that data file, unzip and open it, go to '/yy_mm_dd/yy_mm_dd_sync(or yy_mm_dd_extract)'. There are data from multiple sensors. For 3D GPS/IMU data, please go to 'oxts' folder(thus they use oxts's(Oxford Technical Solutions Ltd) IMU). you can find dataformat, timestamp and dataset of 3D GPS/IMU.
I hope I got that right.

**Comment by hqtang-git** [comment]
Thanks for your meticulous reply! @dohyeoklee 
I think I may not express my purpose clearly, I just want GPS / IMU data rather than all data including video, because the poor network quality and  slow download process . Actually, I don't need the image data for my work.

**Comment by dohyeoklee** [comment]
Oh, I got it. @hqtang-git 
In this repository, there is GPS/IMU dataset for '2011_09_26_drive_0002' sync data. You can use it from 'this_repo/src/oxts'
Or if you want to download specific dataset from above webpage, please let me know what to want and your email address. I will extract only GPS/IMU data for that dataset and send it to you.

**Comment by hqtang-git** [comment]
Thanks for your help. @dohyeoklee 
If you are convenient, can you send me the GPS/IMU text files of  2011_09_26 and 2011_09_30?
If you don't have these two days sync data, could you please extract the GPS/IMU data you have and send it to me .
My email address is hqtang@foxmail.com

Thank you very much for your reply and help！

**Comment by dohyeoklee** [comment]
I sent email to you @hqtang-git 
please check it!

**Comment by hqtang-git** [comment]
@dohyeoklee 
I got it. Thanks for your help very much!
